language: python

services:
  - elasticsearch

matrix:
    include:
        - python: "2.7"
          env: TEST_SUITE=test NOSE_WHERE=archivant
        - python: "2.7"
          env: TEST_SUITE=test NOSE_WHERE=libreantdb
        - python: "2.7"
          env: TEST_SUITE=test NOSE_EXCLUDE='^(archivant|libreantdb)' VERSION_GEVENT=1.0.1
        - python: "2.7"
          env: TEST_SUITE=test NOSE_EXCLUDE='^(archivant|libreantdb)' VERSION_GEVENT=1.0.2
        - python: "2.7"
          env: TEST_SUITE=test NOSE_EXCLUDE='^(archivant|libreantdb)' VERSION_GEVENT=1.1.0
        - python: "2.7"
          env: TEST_SUITE=build_sphinx
        - python: "2.7"
          env: TEST_SUITE=flake

before_install:
    - '[[ -n $VERSION_GEVENT ]] && pip install --force gevent==$VERSION_GEVENT || true'

install:
    - 'if [[ $TEST_SUITE == flake ]]; then pip install flake8; return $? ; fi'
    - 'if [[ $TEST_SUITE != flake ]]; then python setup.py install; return $? ; fi'
    - 'if [[ $TEST_SUITE == build_sphinx ]]; then pip install sphinx; return $? ; fi'

script:
    - 'if [[ $TEST_SUITE == flake ]]; then flake8; return $?; fi'
    - 'if [[ $TEST_SUITE == test ]]; then python setup.py test ; return $?; fi'
    - 'if [[ $TEST_SUITE == build_sphinx ]]; then python setup.py build_sphinx; return $?; fi'
